version: 1.0.0.{build}

image: Ubuntu1804

build: off

clone_folder: /usr/go/src/code.bluelife.at/decke/caronade

environment:
  GOPATH: /usr/go/

stack: go 1.10

before_test:
  - go vet ./...

test_script:
  - go test ./...
